### ISSUE TITLE
Use the bot's own Pi to install the backend locally

### ISSUE THREAD

**Issue by mdingena** [FarmBot/Farmbot-Web-API#253]
You have talked about hosting your own web server to accommodate the user application. Wouldn't it be possible to host it on the bot's Raspberry Pi itself? I'm asking because if I'm to host my own web server running 24/7, I'd want it to consume the least amount of power and I'd probably end up using another Raspberry Pi anyways. So is there any reason I couldn't just do that on the bot's Pi?

**Comment by RickCarlino** [comment]
You could, and I would encourage you to try it out to see if it works for your setup. Here's a couple of things to keep in mind:

1. It *might* be too resource intensive for the Pi. Back in the Pi 1 era, we tried running MongoDB inside the Pi and found that it couldn't handle it. The Pi may be fast enough now (Pi 3), but we haven't tried.
2. You will need to setup port forwarding on your router and possibly maintain a static IP address. Our experience with exposing IP addresses for daily use of the bot has not been good, which is why we avoid it. For more technical users, this might not be such a big deal.

Let us know how it goes. I am curious to see if the new Pi hardware can keep up.

**Comment by RickCarlino** [comment]
Closing this one for now. Feel free to re-open if you have any new developments.

**Comment by toddklaus** [comment]
Hi Rick, was the issue CPU or RAM?  Thanks.

**Comment by RickCarlino** [comment]
@toddklaus It is no longer possible to run a server and FBOS on the same machine without making significant changes to the software (this discussion is from a year ago when things were much different).

With regards to running the server stack on a second RPi: I just bumped in to a developer who tried to run an entire server stack on an RPi (a second device- not the pi) this month while at a convention. After hearing the results, my recommendation is to use a desktop machine on the same LAN if you wish to self host. They had mentioned that the setup and installation on a Pi was extremely time consuming and performance from the server was almost unusable. Using a standard desktop machine was faster in terms of performance, setup time and ease of maintenance.

It might still be possible with overclocking, or using a different brand of SBC but due to the reasons noted above, I no longer recommend it to self hosting users.
