### ISSUE TITLE
Token generation without a 'blessed' account

### ISSUE THREAD

**Issue by Phrohdoh** [FarmBot/Farmbot-Web-API#278]
Is it possible to generate a valid token without a farmbot.io account?
I realize this project is fully F/OSS (which is amazing, great job!) so both sides can be changed as I see fit (no token validation, no token reading at all, etc) but that would probably make upgrading quite difficult.

**Comment by RickCarlino** [comment]
@Phrohdoh Do you mean to ask if it is possible to have a single user setup? The current software was built from the ground up to support multiple accounts on one server, so that is probably outside of the architecture of this project.

That being said, it is an OSS project. If you wish to have a personal server for your own use, the deployment instructions are up-to-date and you could easily stand one up on a VPS or bare metal server on a LAN or behind a firewall.

What kind of use case did you have in mind?

**Comment by Phrohdoh** [comment]
The instructions mention cURL-ing `https://my.farmbot.io/api/tokens` to generate an API token.
Is this something that would exist on my own instance if I were to self-host this?
I'd like to host the software (server and web app) myself keeping all of my data on my own hardware, at least for the time being.

I do not think I will need any more than a single user (as long as a user can manage N FarmBots).

**Comment by RickCarlino** [comment]
@Phrohdoh That is correct. For instance: If you were running the server on your laptop, you would just `curl` to `http://localhost:3000/api/tokens` instead of our server. The server running on your laptop would be identical to the one running on `my.farmbot.io`.

As for the user stuff, you could just create one account and keep the server behind a firewall to prevent outsiders from registering for an account.

**Comment by Phrohdoh** [comment]
Great, thanks for the information!

Unrelated to this issue but, is there an IRC channel (on freenode?) or gitter or anything similar for instant communication? Or is the forum the primary and only means of community communication?

**Comment by RickCarlino** [comment]
@Phrohdoh We don't have one at the moment. Unfortunately, the Gitter chat was eating up a lot of our time on duplicate questions that had already been answered on the forum, so we eventually shut it down in favor of the message board. #farmbot on Freenode is a thing, but none of the core uses it.

Github issues and the forum are the best place to get support for now.
