### ISSUE TITLE
How to set the environment variables "OS_UPDATE_SERVER" and "FW_UPDATE_SERVER"?

### ISSUE THREAD

**Issue by linqingfeng** [FarmBot/Farmbot-Web-API#293]
Hi，

How to set the environment variables "OS_UPDATE_SERVER" and "FW_UPDATE_SERVER"?

We use the local deployment of the environment, but do not know how to build an update server, please tell us how to build?

Thanks very much!

**Comment by RickCarlino** [comment]
Setting ENV vars in Bash / Linux:

```
MQTT_HOST=localhost \
OS_UPDATE_SERVER=https://api.github.com/repos/farmbot/farmbot_os/releases/latest \
FW_UPDATE_SERVER=https://api.github.com/repos/FarmBot/farmbot-arduino-firmware/releases/latest \
 rails s
```

You probably don't want to build an update server by yourself. If you *really do* want to run your own updates channel, you can just fork FarmBot OS and Farmbot Arduino Firmware on Github and point the `OS_UPDATE_SERVER` and `FW_UPDATE_SERVER` to your fork instead of our fork. Again, I do not recomend this because we will only support the latest versions. We don't fix bugs on outdated software versions.

**Comment by linqingfeng** [comment]
@RickCarlino Thanks,that is OK.
