### ISSUE TITLE
languages/ru.js

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/Farmbot-Web-API#296]
I would be happy to help with the translation, if I knew how to do it)

**Comment by RickCarlino** [comment]
@Daniil145 Thanks for your interest in internationalizing the app. This is particularly true for Russian- We're seeing a lot of users with `ru` as their locale. As a side note, internationalization happens in the [Frontend](https://github.com/FarmBot/farmbot-web-frontend/) rather than in the API.

I just added an example file to [/public/app-resources/languages/ru.js](https://github.com/FarmBot/farmbot-web-frontend/blob/master/public/app-resources/languages/ru.js) .

Basically, translating the application to a particular locale involves:

1. Fork this repo
2. Create a `yy.js` file in `/public/app-resources/languages/` where `yy` is your language's [language code](http://www.science.co.il/Language/Locale-codes.php). Eg: `ru` for Russian.
3. Search the application for calls to `t()`. Any file that imports `from "i18next"` will have strings that require translation.
4. When you have updated or added new translations, commit/push your changes and

**Comment by RickCarlino** [comment]
Also, sorry for the delay in responding. It was a holiday in the US last week.

**Comment by Daniil145** [comment]
I dont understand this: "Search the application for calls to t(). Any file that imports from "i18next" will have strings that require translation." I work this ruby or js first

**Comment by RickCarlino** [comment]
@Daniil145 This would be entirely javascript based. You would need to clone [this repo here](https://github.com/FarmBot/farmbot-web-frontend) instead of the API.

**Comment by RickCarlino** [comment]
Closing this issue for now. If you have any more questions, please move the discussion to the [Frontend Repo](https://github.com/FarmBot/farmbot-web-frontend).
