### ISSUE TITLE
What info goes in here? I'm lost!

### ISSUE THREAD

**Issue by carlosen14** [FarmBot/Farmbot-Web-API#319]
I am installing this but I don't get what URL has to be there.

In step 8. `MQTT_HOST=your_mqtt_server_domain rails s`.. this does says a lot, but my doubt is, what do I have to place there if I want to run MQTT host locally?, Also (just if it is posible), what in case I want to use the original farmbot MQTT host?..

I am on mid installing this Web-API.. But i am kind of lost, What do I have to install first or the order doesn't matter installing MQTT, Web-API and Front-End..?

Thanks for the help!

**Comment by RickCarlino** [comment]
Hi @carlosen14 :

1. `MQTT_HOST` must point to the IP address or hostname of the machine running the MQTT server. You cannot put `localhost` or `0.0.0.0` here.
2. It is no longer possible to use the official FarmBot MQTT server on self hosted installations. This is for security reasons. There may still be documentation floating around that says the contrary, but such documentation is out of date. Could you please let me know if you saw that anywhere so that I can update it to reflect the current setup?
