### ISSUE TITLE
Local Install Issue:  key not found: "GCS_BUCKET" (KeyError)

### ISSUE THREAD

**Issue by cmlogan** [FarmBot/Farmbot-Web-API#321]
Hey guys - 

having a small issue with the following: 
7. Verify installation with  RAILS_ENV=test rake db:create db:migrate && rspec spec

returns this error:
/www/Farmbot-Web-API/app/controllers/api/images_controller.rb:3:in `fetch': key not found: "GCS_BUCKET" (KeyError)

Any thoughts?

Thanks in advance

**Comment by RickCarlino** [comment]
@cmlogan Thanks for catching this.

This was a legitimate bug and not an installation mistake. This bug affects users who do not use Google Cloud Storage. Since we use Google Cloud Storage for image processing on the "mainline" server and all of our development machines, we did not see the issue until now.

I have updated the server to store images to disk if Google Cloud Storage is not configured.

Please make sure you delete all variables from `application.yml` that begin with `GCS_` (Eg: `GCS_BUCKET`) if your intention was to store images locally and not use GCS.

Thanks again, and sorry for the confusion.
