### ISSUE TITLE
docker-compose PR?

### ISSUE THREAD

**Issue by creimers** [FarmBot/Farmbot-Web-API#328]
Hi @RickCarlino ,

would you consider to merge a PR adding docker-compose support for the rails + postgres (+ mqtt) stack?

I was helping out somebody on the farmbot europe slack channel the other day with getting everything up and running locally, and in my opinion/experience it would be quite a bit easier if it came down to `docker-compose build && docker-compose up`. 

I've started working on it here: https://github.com/creimers/Farmbot-Web-API/tree/feature/docker-compose

Should you find the time to give it a look, I'm looking forward to receiving feedback.

**Comment by RickCarlino** [comment]
@creimers Sure! I'm sure that would help a lot of people out. Please be sure to write good documentation for it when you do. I will take a look on Monday.

**Comment by RickCarlino** [comment]
@creimers I just took a look. It looks promising! Please let me know if you have any questions.

**Comment by creimers** [comment]
@RickCarlino Yes, I do have a question as a matter of fact.

On a server, the the whole thing will have to run behind lets say nginx. Does it have to expose any crazy ports for the mqtt (and the websockets)? 

Do you have an example nginx config file by chance?

**Comment by RickCarlino** [comment]
@creimers

 * **Running behind NGinx**: [This is our docker config](https://github.com/FarmBot/mqtt-gateway/blob/master/devops_spellbook.sh#L28). We haven't had a need for load balancing (yet), so we've just been running it on a single node, not in front of HAProxy or NGinx. You will need to expose ports `3002`, `80` (mapped to port `3002` on the container), `1883`, and `443`. KEEP IN MIND: Port `1883` is a *plain old TCP socket*. It's not HTTP related. You will need to configure NGinx to run as a traditional TCP (non-http) load balancer for this port. This is just for the MQTT server, which can run separately from the web server. The web API is a pretty standard web server.
 * **NGinx config**: Many moons ago, we ran this server using Dokku, but unfortunately, I've destroyed those VMs in favor letting Heroku handle those details. I don't hve a backup of the NGinx configs. The big thing to look out for with these setups is that port `1883` is not a web port. It runs over standard TCP and has no relation to HTTP. I've hit a lot of issues with automated deployment tools that assume that everything is a web server. Please let me know if you hit any of these issues.

**Comment by Klimbim1** [comment]
Hi @RickCarlino and  @creimers, Christoph was helping me out in installing the web-api locally;

Don't know it it is worth it but I would love to have an update in your README on what exacltly needs to run when I do install it locally; does an MQTT server need to be installed too? do I need to install the frontend as well and run it via npm start? 

I would be fine as well with the docker method if it would work ;)

**Comment by RickCarlino** [comment]
@Klimbim1

**Regarding MQTT**: You must run an MQTT server locally. I have updated the README file to reference this fact. Very early (pre-launch) versions of FarmBot did not require an MQTT server, but that has since been removed for security reasons. If you see any documentation that still references that, please let me know and I can update it accordingly.
**Regarding the Frontend**: Running `./install_frontend.sh` should be enough, unless you plan on writing modifications to the software.
**Regarding Docker Compose**: I made a few updates to the deployment instructions regarding a "bare metal" server deployment. If you have experience with Docker Compose and would like to submit a config file, we would be happy to merge it into the repo or link to your repo. Another alternative to Docker Compose is [Dokku](https://github.com/dokku/dokku), which is what we used at FarmBot, Inc prior to making the switch to Heroku. My experience with Dokku was mostly positive, so it might be another option for containerizing self hosted installations. Dokku deployment instructions are available in `deployment.md`, but they will need to be updated since we made the switch from MariaDB to Postgres. More than happy to help with questions.

Also @creimers please let me know if you have any other questions about the setup. Would love to add this option to the docs or link to it. I am going to close this issue as I feel the main question has been answered.
